name: Deploy WordPress Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        env:
          VITE_BASE_PATH: ./
        run: |
          npm ci
          npm run build

      - name: Guard dist output
        run: |
          test -f dist/index.html || (echo "dist/index.html not found" && exit 1)
          test -f dist/manifest.json || (echo "dist/manifest.json not found" && exit 1)

      - name: Assemble WordPress plugin bundle
        run: |
          rm -rf wordpress-plugin
          mkdir -p wordpress-plugin/ai-lp-embed
          cp -R deliverables/wp-plugin/ai-lp-embed/. wordpress-plugin/ai-lp-embed/
          rsync -av --delete dist/ wordpress-plugin/ai-lp-embed/dist/

      - name: Install sshpass
        run: sudo apt-get update -y && sudo apt-get install -y sshpass

      - name: Prepare remote directory
        env:
          WP_HOST: ${{ secrets.WP_HOST }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_SSH_PASS: ${{ secrets.WP_SSH_PASS }}
          WP_REMOTE_PATH: ${{ secrets.WP_REMOTE_PATH }}
          WP_SSH_PORT: ${{ secrets.WP_SSH_PORT || '22' }}
        run: |
          set -euo pipefail

          sanitize() {
            local value="$1"
            value=${value//$'\r'/}
            value=${value//$'\n'/}
            value="${value#${value%%[![:space:]]*}}"
            value="${value%${value##*[![:space:]]}}"
            printf '%s' "$value"
          }

          PASS_CLEAN=$(sanitize "${WP_SSH_PASS-}")
          HOST_CLEAN=$(sanitize "${WP_HOST-}")
          USER_CLEAN=$(sanitize "${WP_USER-}")
          PORT_CLEAN=$(sanitize "${WP_SSH_PORT-}")
          REMOTE_PATH_CLEAN=$(sanitize "${WP_REMOTE_PATH-}")
          if [[ -z "$PORT_CLEAN" ]]; then
            PORT_CLEAN=22
          fi

          PLUGIN_SLUG="ai-lp-embed"
          REMOTE_BASE="${REMOTE_PATH_CLEAN%/}"
          if [[ -z "$REMOTE_BASE" ]]; then
            echo "WP_REMOTE_PATH is empty after sanitization" >&2
            exit 1
          fi

          if [[ "$REMOTE_BASE" == */$PLUGIN_SLUG ]]; then
            REMOTE_PLUGIN_DIR="$REMOTE_BASE"
          elif [[ "$REMOTE_BASE" == "$PLUGIN_SLUG" ]]; then
            REMOTE_PLUGIN_DIR="$PLUGIN_SLUG"
          else
            REMOTE_PLUGIN_DIR="$REMOTE_BASE/$PLUGIN_SLUG"
          fi

          echo "Preparing remote plugin directory: $REMOTE_PLUGIN_DIR"

          sshpass -p "$PASS_CLEAN" ssh -p "$PORT_CLEAN" -o StrictHostKeyChecking=no "$USER_CLEAN@$HOST_CLEAN" "
            mkdir -p \"$REMOTE_PLUGIN_DIR\" &&
            chmod 755 \"$REMOTE_PLUGIN_DIR\"
          "

      - name: Rsync deploy
        env:
          WP_HOST: ${{ secrets.WP_HOST }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_SSH_PASS: ${{ secrets.WP_SSH_PASS }}
          WP_REMOTE_PATH: ${{ secrets.WP_REMOTE_PATH }}
          WP_SSH_PORT: ${{ secrets.WP_SSH_PORT || '22' }}
        run: |
          set -euo pipefail

          sanitize() {
            local value="$1"
            value=${value//$'\r'/}
            value=${value//$'\n'/}
            value="${value#${value%%[![:space:]]*}}"
            value="${value%${value##*[![:space:]]}}"
            printf '%s' "$value"
          }

          PASS_CLEAN=$(sanitize "${WP_SSH_PASS-}")
          HOST_CLEAN=$(sanitize "${WP_HOST-}")
          USER_CLEAN=$(sanitize "${WP_USER-}")
          PORT_CLEAN=$(sanitize "${WP_SSH_PORT-}")
          REMOTE_PATH_CLEAN=$(sanitize "${WP_REMOTE_PATH-}")
          if [[ -z "$PORT_CLEAN" ]]; then
            PORT_CLEAN=22
          fi

          PLUGIN_SLUG="ai-lp-embed"
          REMOTE_BASE="${REMOTE_PATH_CLEAN%/}"
          if [[ -z "$REMOTE_BASE" ]]; then
            echo "WP_REMOTE_PATH is empty after sanitization" >&2
            exit 1
          fi

          if [[ "$REMOTE_BASE" == */$PLUGIN_SLUG ]]; then
            REMOTE_PLUGIN_DIR="$REMOTE_BASE"
          elif [[ "$REMOTE_BASE" == "$PLUGIN_SLUG" ]]; then
            REMOTE_PLUGIN_DIR="$PLUGIN_SLUG"
          else
            REMOTE_PLUGIN_DIR="$REMOTE_BASE/$PLUGIN_SLUG"
          fi

          sshpass -p "$PASS_CLEAN" rsync -avz --delete \
            -e "ssh -p $PORT_CLEAN -o StrictHostKeyChecking=no" \
            "wordpress-plugin/$PLUGIN_SLUG/" "$USER_CLEAN@$HOST_CLEAN:$REMOTE_PLUGIN_DIR/"

      - name: Show remote listing
        env:
          WP_HOST: ${{ secrets.WP_HOST }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_SSH_PASS: ${{ secrets.WP_SSH_PASS }}
          WP_REMOTE_PATH: ${{ secrets.WP_REMOTE_PATH }}
          WP_SSH_PORT: ${{ secrets.WP_SSH_PORT || '22' }}
        run: |
          set -euo pipefail

          sanitize() {
            local value="$1"
            value=${value//$'\r'/}
            value=${value//$'\n'/}
            value="${value#${value%%[![:space:]]*}}"
            value="${value%${value##*[![:space:]]}}"
            printf '%s' "$value"
          }

          PASS_CLEAN=$(sanitize "${WP_SSH_PASS-}")
          HOST_CLEAN=$(sanitize "${WP_HOST-}")
          USER_CLEAN=$(sanitize "${WP_USER-}")
          PORT_CLEAN=$(sanitize "${WP_SSH_PORT-}")
          REMOTE_PATH_CLEAN=$(sanitize "${WP_REMOTE_PATH-}")
          if [[ -z "$PORT_CLEAN" ]]; then
            PORT_CLEAN=22
          fi

          PLUGIN_SLUG="ai-lp-embed"
          REMOTE_BASE="${REMOTE_PATH_CLEAN%/}"
          if [[ -z "$REMOTE_BASE" ]]; then
            echo "WP_REMOTE_PATH is empty after sanitization" >&2
            exit 1
          fi

          if [[ "$REMOTE_BASE" == */$PLUGIN_SLUG ]]; then
            REMOTE_PLUGIN_DIR="$REMOTE_BASE"
          elif [[ "$REMOTE_BASE" == "$PLUGIN_SLUG" ]]; then
            REMOTE_PLUGIN_DIR="$PLUGIN_SLUG"
          else
            REMOTE_PLUGIN_DIR="$REMOTE_BASE/$PLUGIN_SLUG"
          fi

          sshpass -p "$PASS_CLEAN" ssh -p "$PORT_CLEAN" -o StrictHostKeyChecking=no "$USER_CLEAN@$HOST_CLEAN" "
            ls -la \"$REMOTE_PLUGIN_DIR\" &&
            echo '== dist ==' &&
            ls -la \"$REMOTE_PLUGIN_DIR/dist\" || true &&
            echo '== assets ==' &&
            ls -la \"$REMOTE_PLUGIN_DIR/dist/assets\" || true
          "
